version: '3.9'
name: testing-dev
services:
  api:
    build: ./src
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8000:8000
    env_file: 
      - ./.env.dev
    restart: on-failure
