# Generated by Django 5.0.2 on 2024-02-28 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название продукта')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата старта продукта')),
                ('stop_date', models.DateField(blank=True, null=True, verbose_name='Дата остановки продукта')),
                ('price', models.IntegerField(default=0, verbose_name='Стоимость продукта')),
                ('max_group_size', models.IntegerField(default=5, verbose_name='Максимум студентов в группе')),
                ('min_group_size', models.IntegerField(default=1, verbose_name='Минимум студентов в группе')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=150, verbose_name='Тема урока')),
                ('video_url', models.URLField(max_length=150, verbose_name='Ссылка на видео урока')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_learning.product', verbose_name='Продукт урока')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс студента')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='students',
            field=models.ManyToManyField(related_name='products', to='product_learning.student', verbose_name='Студенты курса'),
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название группы')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_learning.product', verbose_name='Продукт группы')),
            ],
            options={
                'verbose_name': 'Группа студентов',
                'verbose_name_plural': 'Группы студентов',
                'ordering': ['-id'],
            },
        ),
    ]
