# Generated by Django 5.0.2 on 2024-02-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_learning', '0003_studentgroup_students_alter_lesson_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='product_learning.product', verbose_name='Продукты студента'),
        ),
    ]
