# Generated by Django 5.0.2 on 2024-02-28 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_learning', '0004_remove_product_students_student_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_groups', to='product_learning.product', verbose_name='Продукт группы'),
        ),
    ]
