# Generated by Django 5.0.2 on 2024-02-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_learning', '0005_alter_studentgroup_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='students', to='product_learning.product', verbose_name='Продукты студента'),
        ),
    ]
